version: '3.8'
services:
  app:
      build: .
      container_name: quiz-app
      ports:
      - '3000:3000'
      restart: always
      volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      depends_on:
        - db
        - cache
  db:
    image: mysql:8.0
    restart: always
    container_name: quiz-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3303:3306'
  cache:
    image: redis:6.2-alpine
    container_name: quiz-cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
volumes:
  mysql-data:
  cache:
    driver: local

